#!/bin/bash -e
git clone https://github.com/tgockel/json-voorhees.git
cd json-voorhees
[[ -n $(git config user.name) ]] || git config user.name "nobody"
[[ -n $(git config user.email) ]] || git config user.email "nobody@nowhere"
git checkout -b stg_patched $(cat ../patches/series | head -1 | awk '{print $NF}')
stg init
stg import --series ../patches/series
